<?php

/***************************************************************************
      This file was automatically generated by Admin FAQ Editor
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

//
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//

$faq[] = array("--", "Contents");
$faq[] = array("What is the MX-portal project all about? ", "<P>MX-portal is an addon portal CMS for phpbb forums, hosted at <A href=\"http://www.mx-publisher.com\">www.mx-publisher.com</A>.Unlike most portals or addons for phpbb mx system relies on a modular system, to provide a wide range of features including, news, downloads, albums and many others including third parties. The advantage of this modular system is that a module may be installed and administered without touching code </P>");
$faq[] = array("What are the requirements for running MX-portal? ", "- PHP4+
<br />- PHPBB 2.0x (latest version)
<br />- MySQL or postresSQL Db's
<br />
<br />Certain modules may require other requirements
<br />recomended setup
<br />
<br />- PHP4.3.3 or greater with safe mode off
<br />- PHPBB 2.0x (latest version)
<br />- MySQL 4.0");
$faq[] = array("How do i install/uninstall/upgrade the MX-portal? ", "Detailed installation instructions are given in the main <a href=http://www.mx-publisher.com/forum/viewtopic.php?t=1224>MX CORE RELEASE thread</a> a copy of which can be found in the core install. Anyone familiar with phpbb install will find mx install a breeze. Before starting make sure you have your db details and path to phpbb to hand. During the install its recomended you switch the default and admin theme to subSilver and the default and admin language to English, individual themes and languages can be added afterwards.");
$faq[] = array("What's all this talk about modules? ", "MX-portal is modular, i.e. additional features extending the MX CORE are installed and handled as modules. These modules are released and maintained individually, and may also be written by the user himself. Popular modules are for example Album and download addons, knowledge base addon (this FAQ) and news managing systems...");
$faq[] = array("How do i install/uninstall/upgrade modules? ", "Each module has its own release and install thread. Check out the <a href=http://www.mx-publisher.com/forum/viewforum.php?f=11>release forum</a> for official modules releases and the < href=http://www.mx-publisher.com/forum/viewforum.php?f=31>beta/3rd party release forums</a> for user contributed modules.");
$faq[] = array("Common installation problems... ", "First of all, you may want to validate all path settings were defined correctly for mx during install:
<br />
<br />Validate the database path settings:
<br />Browse to http://www.yourdomain.com/portaldir/admin/admin_mx_portal.php directly and validate current mx and phpbb paths.
<br />
<br />For example:
<br />
<br />mx path: http://www.yourdomain.com/mx/
<br />phpbb path: http://www.yourdomain.com/phpbb2/
<br />
<br />note: the traling slashes are important!
<br />
<br />Validate relative phpbb path
<br />Open the mx config.php file and checkout the relative phpbb path
<br />
<br />For example:
<br />
<br />../../../forum/ = ../../../ . '../phpbb2/';
<br />
<br />No other environmental paths are defined for mx!
<br />
<br />Be sure to consult the install docs once more for more detailed info.
<br />
<br />OTHER PROBLEMS:
<br />
<br />Quote:
<br />Funny path: ...admin/admin/...
<br />
<br />This problem occurs when the MX paths are not correctly entered in the db during installation. Typically this happens if you call the mx_db_install.php file directly (and not mx_install.php as you're supposed to). You may either enter them directly in the db using phpmyadmin (or similar) or browse to the MX General Setup Page (yourmxurl/admin/admin_mx_portal.php) in the adminCP and edit according to instructions given in the main installation docs.
<br />
<br />Quote:
<br />\"Could not query database for theme info\"
<br />
<br />Be sure either old mx config.php is deleted or emptied before attempting to install/upgrade mx
<br />
<br />Quote:
<br />Known issues with some phpbb mods and MX
<br />
<br />- File Attachment mod is working fine with mx
<br />- Cash mod is problematic...we're trying to find a cure...
<br />
<br />Quote:
<br />\"Call to undefined function: include_attach_lang()\"
<br />
<br />This error mess has nothing to do with File Attachment mod...it's due to badly set db prefixes in the mx config.php. Be sure to validate the settings.
<br />
<br />Quote:
<br />Left frame entries are missing in AdminCP after MX installation
<br />
<br />You're using themes in phpbb not yet installed for mx. Switch back to subSilver or install the theme for mx.
<br />
<br />Quote:
<br />\"Cannot add header information - headers already sent by\"
<br />
<br />This error may occur in numerous situations: the mx files are uploaded to wrong place, the mx cahce file is unwritable, you have edited files incorrectly, you have a incompatible module installed or the module is buggy...thus this problem is hard to pinpoint and should be debugged in the support forums
<br />
<br />Quote:
<br />GZip, Server cache and other server related issues
<br />
<br />Some servers feature cache and compression, which may distrurb the mx cache...
<br />
<br />Further reading:
<br />How to solve the ob_gzhandler problem
<br />
<br />Quote:
<br />\"Template->make_filename(): Error - file overall_header.tpl does not exist\"
<br />
<br />You're using themes in phpbb not yet installed for mx. Switch back to subSilver or install the theme for mx.
<br />
<br />Quote:
<br />Information
<br />Your mx-portal or module need to be upgraded, since its calling an old mx function include file. If you are coding yourself be sure to include the phpbb includes version of \" bbcode.php \" instead, i.e. replace mx_root_path with phpbb_root_path in the include call...
<br />
<br /><a href=http://www.mx-publisher.com/forum/viewtopic.php?t=4100>http://www.mx-publisher.com/forum/viewtopic.php?t=4100</a>");
$faq[] = array("How does the AdminCP work for managing the portal? ", "In short, the portal consists of one or more pages (referred to by page=id in the url), and every page is composed of blocks. The MX core provide several types of basic blocks, for example textblocks, last message block, who's online block etc. Installed mx modules provide additional blocks designed for specific use.
<br />
<br />Further reading:
<br /><a href=http://www.mx-publisher.com/index.php?page=108&mode=article&k=1>- The Mx Portal Admin Panel - How does it work?<a>");
$faq[] = array("What about cache? ", "The MX-portal uses a cache feature, for faster page generation time. You may disable the cache by deleting the two *.xml files in the cache folder.
<br />Also make sure the cache folder, and its files are writable.");
$faq[] = array("Languages", "The MX-portal is multilangual, and all contributed translations are uploaded/found in the mx downlolad area.
<br />
<br />Languages are installed by uploading the lang_ folder to the mx lang dir.
<br />modules also have their own language and template modules
<br />
<br />Note: If you've done a translation, please share (upload)...");
$faq[] = array("Themes ", "The MX-portal support standard phpbb themes, and all contributed themes are uploaded/found in the mx downlolad area.
<br />
<br />Themes must first be installed for phpbb, THEN for mx.
<br />
<br />Note: If you've done a cool theme, please share (upload)...");
$faq[] = array("I want to add my own theme/style - help? ", "A basic understanding of the phpbb themes approach is required and newbies should really start reading some introductory articles over at phpbb.com.
<br />
<br /><a href=http://www.mx-publisher.com/index.php?page=108&mode=cat&cat=4>Further reading</a>
<br />
<br />Themes are held in 2 places, for the core they are held in templates folder the layout is similar to that of phpbb with each theme having its own folder. Modules also hold themes in a template folder unlike the core most modules have a default theme that is used if the users current theme does not have any special templates.");
$faq[] = array("How come MX and phpbb have different headers (top navigation) - help? ", "MX and phpbb are still two different site areas, and use each its own overall_header.tpl file...this is since mx is a phpbb addon and do not modify any phpbb files.
<br />
<br />To make the site more mx-phpbb integrated, you need to edit the phpbb overall_header yourself making it look and feel like the portal's.
<br />
<br /><a href=http://www.mx-publisher.com/index.php?page=108&mode=cat&cat=4>Further reading</a>");
$faq[] = array("I did try searching, but failed...?? ", "The phpBB search function is not very effective when common search phrases are used. Try to make your search more specific. But we stress the search function itself IS working. ");
$faq[] = array("I want to create my own module - help? ", "Module development is pretty easy, once you've come to understand the basic hierarchy of mx and modules...and if knowing some php  Mostly you start off from a phpbb mod (released over at phpbb.com) and adapt it for mx...
<br />
<br /><a href=http://www.mx-publisher.com/index.php?page=108&mode=cat&cat=3>Further reading</a>
<br />
<br />please don't forget to share your modules with others!");
$faq[] = array("Becoming a MX developer...using cvs ", "We are always looking for extra hands both in development and bug/beta tracking. Normally would be developers do a stint as bug trackers before joining the development team though it has been known for invitations to be issued to php developers from time to time. For more information on becoming a developer or bug tester please contact Haplo or Drift");
$faq[] = array("When is the next release / Can I test it? ", "We have learned from bitter experience not to give definate dates for releases though it is usually obvious by the hive of activity when such releases occur. In january 2004 we released mx 2.71rc this was our first fully supported stable version, and it is this that is the current basis development work, subsequent recent releases have been bug fixes. Plans for version mx3 are in the making.
<br />
<br />How can you test up and coming releases?
<br />Simply join the bug testing group, and start submitting bugs. beta testing is our way of saying thanks though since it usually involves yet more testing its something of a double edged sword ");
$faq[] = array("How's the MX project organized? ", "The MX-portal was founded by MarcMoris, but this dev site is currently supervised by Haplo and Drift.
<br />The Dev team are a mix of developers and coders from varying backgrounds. Togeather with the bug testers they try to expand mx into the best modular cms for phpbb their is.");



?>