<?php

/***************************************************************************
      This file was automatically generated by Admin FAQ Editor
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

//
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//

$faq[] = array("--", "Faq & Rules Faq");
$faq[] = array("What is Faq & Rules module?", "Faq & Rules module is an script can permit to manage Frequently Answered Question and Rules for your portal, you can modify faq and rules directly from ACP.");
$faq[] = array("How can i add faq in my modules?", "Is simple you just to add an file called lang_faq.php into language\lang_*\ in your modules folder, compiled in phpbb faq system.");
$faq[] = array("Where i can submit my faq?", "Feel free to modific portal faqs they are just doned copying MX-Publisher ones");
$faq[] = array("Can i manage modules faq from acp?", "Not in this version, the module faq management is too hard to develope, maybe in future");
$faq[] = array("Who has write this module?", "This module is an modified-ported version of numerous script:
<br />Faq Original system by <a href=http://www.phpbb.com>PhpBB</a>
<br />Editor system by <a href=http://phpms.sourceforge.net>Selven</a>
<br />Faq Dhtml Collapsible system by <a href=http://www.phpmix.com>Markus Petrux</a>
<br />Rules system by <a href=http://www.phpbb.com/community/viewtopic.php?f=15&t=423664>eviL&lt;3</a>");?>