<?php
/**
*
* @package mxBB Portal Core
* @version $Id: mx_meta.inc,v 1.2 2009/01/24 16:47:51 orynider Exp $
* @copyright (c) 2002-2006 mxBB Project Team
* @license http://opensource.org/licenses/gpl-license.php GNU General Public License v2
* @link http://www.mx-publisher.com
*
*/

 $title       = "Your site's title";
 $author      = "Your name or your company name";
 $copyright   = "Add some copyright notice here";
 $keywords    = "Add all your keywords in here (separate each keyword by a comma and space)";
 $description = "This is the description search engines show when listing your site.";
 $langcode    = "en";
 $rating      = "general";
 $index       = "index";
 $follow      = "follow";
 $pragma      = "1";
 $icon        = "favicon.ico";
 $header      = "<meta name=\"revisit-after\" content=\"7 days\" >";
?>