<?php
/** 
*
* lang_faq [Turkish]
*
* @package language
* @version $Id: lang_faq.php,v 1.2 2007/03/23 21:22:22 angelside Exp $
* @copyright (c) 2005 phpBB Group 
* @license http://opensource.org/licenses/gpl-license.php GNU Public License 
*
*/
 
// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//


$faq[] = array("--","Oturum ve Hesap Açma sorunlarý");
$faq[] = array("Neden oturum açamýyorum?", "Hesap açtýnýz mý? Oturum açabilmek için önceden hesap açmanýz gerek. Yoksa mesaj panosundan atýldýnýz mý (o halde bu anlamda bir mesaj görmeniz gerekir)? Eðer öyleyse, site veya pano yöneticisiyle irtibata geçip sebebini sorabilirsiniz. Eðer hesap açtýysanýz ve yasaklanmýþ olmamanýza raðmen oturum açamýyorsanýz, tekrar tekrar kullanýcý adýnýzý ve parolanýzý kontrol edin. Genelde hata burada oluyor. Sorun bu deðilse pano yöneticisiyle irtibata geçin, belki pano için yanlýþ ayar yapmýþ olabilir.");
$faq[] = array("Neden hesap açmam gerekiyor?", "Hesap açmanýza gerek olmayabilirdi aslýnda. Ýleti gönderebilmek için hesap açmanýn þart olmasý, pano yöneticisinin kararýna baðlý. Ayrýca hesap açýnca bazý özel imkanlara ulaþabilirsiniz. Örneðin iletilerinizin yanýnda kedinize ait küçük bir resim (avatar/sembol) gösterme, özel mesaj gönderme, tanýdýðýnýz kullanýcýlara e-posta gönderme veya kullanýcý gruplarýna katýlma imkanlarýna misafir kullanýcýlar sahip deðildir. Hesap açma iþlemi çok basit olduðu için hesap açmanýz önerilir.");
$faq[] = array("Neden otomatik olarak oturum kapatýlýyor?", "Oturum açma sayfasýnda gördüðünüz <i>Beni hatýrla</i> komutunu seçmediðiniz sürece, mesaj panosu sizi sadece belirli bir süre için oturum açmýþ kabul eder. Böylece hesabýnýzýn baþkalarý tarafýndan kullanýlmasý önlenir. Oturumunuzun devamlý kalmasý için, bu komutu seçmeniz yeterlidir. Fakat baþka þahýslarýnda kullandýðý (örn. herhangi bir kütüphaneye, internet cafeye, üniversiteye vs. ait) bir bilgisayardan oturum açýyorsanýz yapýyorsanýz, bu komutu seçmemeniz önerilir.");
$faq[] = array("Kimler Çevrimiçi listesinde ismimin görülmesini nasýl önleyebilirim?", "Þahsýnýza ait hesabýnýz sayfasýnda <i>Çevrimiçi olduðumu gizle</i> seçeneðini bulabilirsiniz. Buradan <i>Evet</i> 'i seçince çevrimiçi olduðunuzu sadece pano yöneticileri ve kendiniz görebilirsiniz. Bu durumda gizli kullanýcý olarak sayýlýrsýnýz.");
$faq[] = array("Parolamý unuttum!", "Telaþa kapýlmayýn! Eski parolanýzý öðrenmek mümkün olmasa bile, yerine deðiþik bir parola alabilirsiniz. Oturum açma sayfasýný açýp <u>Parolamý Unuttum</u> üzerini týklayýn ve tarif edilen iþlemleri uygulayýn. Kýsa sürede tekrar çevrimiçi olduðunuzu göreceksiniz.");
$faq[] = array("Hesap açtým ama oturum açamýyorum!", "Ýlk önce kullanýcý adýnýzý ve parolanýzý doðru yazdýðýnýzý emin olun. Hesabýnýzýn onaylanmasý gerekebilir. Bazý mesaj panolarý tüm yeni açýlan hesaplarýn onaylanmasýný þart koþar. Oturum açabilmeniz yapabilmeniz için ya kendiniz ya da pano yöneticisi tarafýndan hesabýnýz onaylanmalýdýr. Bu durumda onay gerekçesi, hesap açma esnasýnda size bildirilmiþ olmalý. Bu doðrultuda bir e-posta aldýysanýz, tarif edilen iþlemleri uygulamanýz gerek. Eðer böyle bir e-posta almadýysanýz, verdiðiniz e-posta adresinin doðru olup olmadýðýný kontrol edin. Onay gerekçesinin sebebi, <i>kötü amaçlý</i> kullanýcýlarýn anonim kullanýcýlarýn panoyu suistimal etmelerini önlemektir. Verdiðiniz e-posta adresinin doðru olduðundan eminseniz, pano yöneticisiyle irtibata geçmeniz gerekir.");
$faq[] = array("Daha önceleri hesap açmýþtým ama artýk oturum açamýyorum!", "Bunun en olasý sebebi hatalý kullanýcý adý veya parola giriþidir (hesap açtýktan sonra aldýðýnýz e-posta'ya bakýp kontrol edin). Belki de pano yöneticisi hesabýnýzý herhangi bir sebepten dolayý silmiþ olabilir. Panoya hiç ileti gönderdiniz mi? Veritabanýnýn kapladýðý alaný küçük tutmak için, ileti göndermeyen kullanýcýlarýn hesabý genelde belirli bir süre sonra silinir. Tekrar hesap açmayý deneyin.");

$faq[] = array("--","Kullanýcý Seçenekleri ve Ayarlarý");
$faq[] = array("Kullanýcý ayarlarýmý nasýl deðiþtirebilirim?", "Eðer hesap açtýysanýz bütün ayarlarýnýz veritabanýna kaydedilir. Ayarlarýnýzý deðiþtirmek için (genelde sayfalarýn üst kýsmýnda bulunan) <u>Hesabýnýz</u> linkini týklayýn. Ayarlarýnýz buradan deðiþtirilir.");
$faq[] = array("Gösterilen saatler yanlýþ!", "Gösterilen saatler büyük bir ihtimalle doðrudur. Fakat gördüðünüz saat, bulunduðunuz yerin saat diliminden farklý olabilir. Bu durumda, <u>Hesabýnýz</u> linkini týklayýp kendiniz için geçerli saat dilimini seçmeniz gerekir, örn. London, Paris, New York, Sydney vs. Çoðu seçenekler için geçerli olduðu gibi, saat dilimini deðiþtirme imkaný da sadece hesap açmýþ kullanýcýlara verilmiþtir.");
$faq[] = array("Deðiþik bir zaman dilimi seçtim ama saatler hala yanlýþ!", "Doðru zaman dilimini seçtiðinizden eminseniz ve saat hala yanlýþ gösteriliyorsa, bunun en olasý sebebi günýþýðýndan yararlanma deðiþimleri olabilir. Örn. yaz aylarýnda görülen saatler, bulunduðunuz ülkenin gerçek saatinden bir saat ileri veya geri olabilir. Mesaj panosu bu deðiþimleri dikkate almaz.");
$faq[] = array("Konuþtuðum lisan listede yok!", "Bunun en olasý sebepleri, pano yöneticisin konuþtuðunuz lisaný destekleyen uzantýyý kurmamýþ olabilir, ya da bu panonun konuþtuðunuz lisana henüz çevrilmiþ olmayýþýdýr. Pano yöneticilerine baþvurup, kendi lisanýnýzý destekleyen uzantýyý kurmalarýný rica edin. Eðer böyle bir uzantý yoksa, panoyu kendi dilinize çevirmekte özgürsünüz. Bu konuda daha geniþ bilgi için sayfalarýn alt kýsmýnda görülen phpBB Group linkini týklayýn.");
$faq[] = array("Ýsmimin altýnda resim (avatar/sembol) göstermek için ne yapmalýyým?", "Ýletilerin görüntülendiði sayfalarda kullanýcý adlarýnýn altýnda iki tür resim görebilirsiniz. Birincisi, kullanýcý derecenizi gösterir ve genelde gönderdiðiniz ileti sayýsýna baðlý olarak belirli bir sayýda yýldýz veya kare þeklindedir. Bunun altýnda kiþisel sembol denen biraz daha büyük bir resim görebilirsiniz. Bu resim genelde kullanýcýya ait ve özeldir. Kiþisel sembol kullanma imkanýný pano yöneticisi belirler. Ayrýca sembollerin ne þekilde kullanýlabileceðinide belirler. Sembol kullanamýyorsanýz, pano yöneticisine baþvurup bu imkaný ne sebepten iptal ettiðini öðrenebilirsiniz (bunun önemli bir sebebi olduðundan eminiz!)");
$faq[] = array("Kullanýcý derecemi nasýl deðiþtirebilirim?", "Genelde kullanýcý derecenizi doðrudan deðiþtirmeniz mümkün deðil (kullanýcý derecesi, gönderdiðiniz iletinin yanýnda bulunan adýnýzýn altýnda ve kullanýcý bilgileri sayfasýnda görülür). Çoðu mesaj panosunda kullanýcý dereceleri, gönderilen iletilerin sayýsýný veya yetkili üyeleri belirlemek için kullanýlýr, örn. yöneticiler veya pano yöneticileri özel bir dereceye sahip olabilir. Lütfen gereksiz yere ileti gönderip, derecenizi yükseltmeye çalýþmayýn, elde edeceðiniz tek sonuç, yöneticilerin iletilerinizin sayýsýný düþürmesi olacaktýr.");
$faq[] = array("Bir kullanýcýnýn e-posta linkini týklayýnca oturum açmam isteniyor?", "Panoya ait e-posta formuyla maalesef sadece hesabý olan kullanýcýlar e-posta gönderebiliyor (ayrýca yöneticinin bu iþlevi çalýþtýrmasý gerek). Bunun sebebi, e-posta sisteminin anonim kullanýcýlar tarafýndan suistimal edilmesini önlemektir.");

$faq[] = array("--","Konu/Ýleti Gönderme");
$faq[] = array("Foruma yeni konu nasýl gönderilir?", "Çok basit; forumu veya konuyu görüntüleme sayfasýnda <i>Yeni Konu Gönder</i> düðmesine týklayýn. Yeni konu göndermeden önce hesap açmanýz gerekebilir. Forum ve konu sayfalarýnýn alt kýsmýnda yapabileceðiniz bütün iþlemlerin listesini görebilirsiniz (örn. <i>Bu forumda yeni konular açabilirsiniz</i> vs. gibi).");
$faq[] = array("Ýletiler nasýl deðiþtirilir veya silinir?", "Pano yöneticisi veya bölüm yetkilisi olmadýðýnýz sürece, sadece kendinize ait iletileri deðiþtirebilir veya silebilirsiniz. Gönderdiðiniz bir iletiyi <i>Deðiþtir/Düzenle</i> düðmesini týklayarak deðiþtirebilirsiniz (bu imkan bazen sadece belirli bir süre için mevcuttur). Ýletinize birileri cevap göndermiþse eðer, iletinizin altýnda metni kaç defa deðiþtirdiðinizi gösteren kýsa bir yazý göreceksiniz. Ýletiniz henüz yanýtlanmamýþsa, bu not görülmez. Ayrýca iletiniz pano yöneticileri veya bölüm yetkilileri tarafýndan deðiþtirilince de bu yazý görülmez (yöneticilerin böyle bir durumda metnin hangi kýsmýný ne sebepten dolayý deðiþtirdiklerini yazmalarý önerilir). Bir iletiye cevap geldikten sonra normal kullanýcýlar tarafýndan silinemez.");
$faq[] = array("Ýleti altýna imza nasýl eklenir?", "Herhangi bir iletiye imzanýzý ekleyebilmek için önce <i>Hesabýnýz</i> sayfanýza girip bir imza hazýrlamanýz gerek. Daha sonra ileti gönderme formunun alt kýsmýndaki <i>Ýmzamý ekle</i> seçeneðini seçip iletinize imzanýzý ekleyebilirsiniz. Gönderdiðiniz bütün iletilere genel bir ayar olarak imzanýzýn eklenmesini istiyorsanýz, <i>Hesabýnýz</i> sayfasýndaki seçeneði týklayýn. Buna raðmen dilediðiniz her ileti için imzanýzýn eklenmesini önleyebilirsiniz (ileti gönderme formunda <i>Ýmzamý Ekle</i> seçeneðinin iþaretini kaldýrmanýz yeterli).");
$faq[] = array("Anket nasýl hazýrlanýr?", "Anket hazýrlamak çok basit: yeni bir konu gönderirken (veya bir konunun ilk iletisini deðiþtirirken - bu tabi yetkinize baðlý), ileti gönderme formunun altýnda <i>Anket Ekle</i> formunu göreceksiniz (böyle bir formu göremiyorsanýz, anket ekleme yetkiniz yok demektir). Anket sorusunu ve en az iki tane anket þýkký eklemeniz gerekir. Anket þýkký eklemek için <i>Bu Þýkký Ekle</i> düðmesini týklayýn. Ayrýca anketin gösterim süresinide belirleyebilirsiniz, 0 (sýfýr) süresiz demektir. Eklenebilecek anket þýklarýnýn sayýsý sýnýrlýdýr. Bu sýnýrý pano yöneticisi belirler.");
$faq[] = array("Bir anket nasýl deðiþtirilir veya silinir?", "Anketler de iletiler gibi sadece gönderen kullanýcý, bölüm yetkilisi veya pano yöneticisi tarafýndan deðiþtirilebilir. Bir anketi deðiþtirmek için, konunun ilk iletisini týklayýn (ilgili anket daima bu iletiye baðlýdýr). Ankete henüz katýlan olmadýysa, hazýrlayan kullanýcý tarafýndan deðiþtirilebilir veya silinebilir. Ankete katýlan olmuþsa, sadece forum ve pano yöneticileri tarafýndan deðiþtirilebilir veya silinebilir. Böylece bir süre sonra þýklarý deðiþtirip anket sonuçlarýný sapýtma olanaðý kalmaz.");
$faq[] = array("Anketlere neden katýlamýyorum?", "Anketlere sadece hesabý oplan kullanýcýlar katýlabilir (böylece hile yapma olanaðý önlenmiþ olur). Eðer hesap açmanýza olmanýza raðmen anketlere katýlamýyorsanýz, gerekli yetkilere sahip deðilsiniz demektir.");
$faq[] = array("Bazý forumlara neden ulaþamýyorum?", "Bazý forumlar sadece belirli kullanýcýlara veya kullanýcý gruplarýna açýk olabilir. Ýletileri okumak, görüntülemek, göndermek için vs. özel yetki gerekebilir. Bu yetkiyi sadece pano yöneticileri verebilir, bu kiþilere baþvurmalýsýnýz.");

$faq[] = array("--","Biçimlendirme ve Konu Tipleri");
$faq[] = array("Biçim Kodlarý (BBCode) nedir?", "Biçim Kodlarý HTML'in özel bir uygulamasýdýr. Forum'lara yazdýðýnýz iletilerde Biçim Kodlarý kullanabilme imkanýný pano yöneticisi belirler. Ayrýca ileti gönderme formundaki seçenekler sayesinde dilediðiniz iletilerde Biçim Kodlarý'larýný iptal etmeniz mümkündür. Biçim Kodlarý, HTML'e benzer tarzdadýr fakat wtiketler &lt; ve &gt; yerine köþeli parantez içine alýnýr: [ ve ]. Ayrýca nelerin nasýl görüntülendiði daha iyi kontrol edilebilir. Biçim Kodlarý hakkýnda daha geniþ bilgiler için, ileti gönderme sayfasýndan ulaþabileceðiniz <a href='faq.php?mode=bbcode' target='_blank'>rehbere</a> bakýnýz.");
$faq[] = array("HTML kullanabilir miyim?", "Pano yöneticisinin izin vermesine baðlýdýr, ilgili ayarlarýn tümünü o kontrol eder. Eðer izin verilmiþse, büyük ihtimalle sadece bazý etiketlerin çalýþtýðýný göreceksiniz. Böyle olmasý <i>güvenlik</i> içindir. Amaç, pano görüntüsünün bozulmasýný veya daha deðiþik sorunlarýn meydana gelmesini önlemektir. Ýzin verilmiþ olsa bile, ileti gönderme formundaki seçenekler sayesinde dilediðiniz iletilerde HTML'i iptal etmeniz mümkündür.");
$faq[] = array("Ýfade nedir?", "Ýfade (Smiley veya Emoticon), belirli duygu ifadelerini vermek için kullanýlan iþaretlerdir. Metinde küçük resimler halinde görüntülenir. Örn. :) mutlu, :( ise üzgün anlamýndadýr. Kullanabileceðiniz ifadelerin <a href='posting.php?mode=smilies' target='_blank'>listesini</a> ileti gönderme formunda görebilirsiniz. Ýfadeleri aþýrý derecede kullanmamaya özen gösterin, yoksa metin okunmaz hale gelebilir. Bu durumda yönetici ifadeleri veya iletilerinizi tamamýyla silmeye karar verebilir.");
$faq[] = array("Resim gönderebilir miyim?", "Gönderdiðiniz ileti ile beraber resim de görüntülenebilir. Fakat þu anda panoya doðrudan resim göndermek mümkün deðildir. Bu yüzden umuma açýk bir web sitesinde kayýtlý bir resme link vermeniz gerek, örn. http://www.umuma-acik-site.net/resim.gif. Kendi bilgisayarýnýzda bulunan bir resme link vermeniz mümkün deðil. Ayrýca, umuma açýk olmayan ve sadece parolayla ulaþýlan resimlere link vermek mümkün deðildir (örn. hotmail veya yahoo gelen kutusunda vs. kayýtlý resimler). Resim görüntülemek için, Biçim Kodlarý'nýn [img] etiketini ya da (izin verilmiþse) HTML kullanabilirsiniz.");
$faq[] = array("Duyuru nedir?", "Duyurular çoðu zaman önemli bilgileri içerir, en kýsa zamanda okumanýzý öneririz. Duyurular, ilgili forumun her sayfasýnýn baþýnda görülür. Duyuru gönderebilmeniz için bu yetkiye sahip olmanýz gerek. Yetkilerinizi ise pano yöneticisi belirler.");
$faq[] = array("Önemli konular nedir?", "Önemli konular, ilgili forumun ilk sayfasýnda, duyurularýn hemen altýnda görülür. Çoðu zaman önemli bilgileri içerirler, mümkünse okumanýzý öneririz. Duyurular için geçerli olduðu gibi, herhangi bir foruma önemli konu göndermek için gereken yetkileri pano yöneticisi belirler.");
$faq[] = array("Kilitli konular nedir?", "Bu konularý bölüm yetkilisi veya pano yöneticisi kilitler. Kilitli konularý yanýtlamak mümkün deðildir, içerdikleri anketler otomatik olarak sonlandýrýlýr. Konular birçok nedenden dolayý kilitlenmiþ olabilir.");

$faq[] = array("--","Kullanýcý Seviyeleri ve Gruplarý");
$faq[] = array("Pano yöneticileri nedir?", "Pano yöneticileri, panonun her bölümünde en çok yetkiye sahip olan þahýslardýr. Bu kiþiler, panonun her türlü iþlevini kontrol edebilir: izin verme, yetkilendirme, kullanýcý yasaklama, kullanýcý gruplarý yaratma, bölüm yetkilisi yetkilerini verme vs. Ayrýca bütün forumlarda bölüm yetkilisi yetkilerine sahiptirler.");
$faq[] = array("Bölüm yetkilileri nedir?", "Bölüm yetkilileri, günlük olarak forumun çalýþmasýný kontrol eden þahýslar veya gruplardýr. Konularý deðiþtirme ve silme yetkisine sahiptirler. Ayrýca yönettikleri forumdaki konularý kilitleyebilir, taþýyabilir, silebilir ve bölebilirler. Genelde bölüm yetkililerinin görevi, <i>off-topic</i>, yani baþlýk konusuyla ilgisi olmayan yanýtlarýn veya hakaret ve saldýrý niteliðindeki metinlerin gönderilmesini önlemektir.");
$faq[] = array("Kullanýcý gruplarý nedir?", "Kullanýcý gruplarý, pano yöneticilerinin kullanýcýlarý grup halinde ayýrabilmesi için öngörülen bir yöntemdir. Her kullanýcý (çoðu panolardan farklý olarak) birçok gruba üye olabilir. Bu þekilde pano yöneticileri belirli kullanýcýlara rahatlýkla bölüm yetkilisi yetkilerini veya özel forumlara ulaþma yetkisini vs. verebilir.");
$faq[] = array("Bir kullanýcý grubuna nasýl üye olabilirim?", "Bir kullanýcý grubuna üye olmak için, sayfa baþýndaki kullanýcý gruplarý linkine týklayýn. Kullanýcý gruplarýnýn listesini göreceksiniz. Gruplarýn tümü <i>eriþime açýk</i> olmayabilir, bazýlarý kilitli veya gizli olabilir. Grup açýk ise, ilgili düðmeyi týklayarak üye olmak için istekte bulunabilirsiniz. Ýsteðinizin kullanýcý grubu yöneticisi tarafýndan onaylanmasý gerekir, örneðin isteðinizin nedenini sorabilir. Ýsteðiniz reddedilirse grup yöneticisini lütfen rahatsýz etmeyin, bunun nedenleri olsa gerek.");
$faq[] = array("Bir kullanýcý grubunun yöneticisi olmak için ne yapmam gerek?", "Kullanýcý gruplarý pano yöneticisi tarafýndan açýlýr. Pano yöneticisi ayný zamanda her grubun yöneticisini belirler. Eðer yeni bir kullanýcý grubu açmak istiyorsanýz, ilk önce pano yöneticisiyle irtibata geçmeniz gerek, kendisine özel mesaj göndermeyi deneyin.");

$faq[] = array("--","Özel Mesajlar");
$faq[] = array("Özel mesaj gönderemiyorum!", "Bunun üç sebebi olabilir: henüz hesap açmamýþ veya oturum açmamýþsýnýz, veya pano yöneticisi bütün pano için özel mesajlarý iptal etmiþ. Üçüncü olanak ise: pano yöneticisi sizin bu imkaný kullanmanýzý önlemiþ olabilir, bu durumda kendisine nedenini sorabilirsiniz.");
$faq[] = array("Ýstemediðim özel mesajlarý almaya devam ediyorum!", "Ýleride özel mesajlar sistemine belirli kiþilerden gelen mesajlarý iptal etme imkanýný ekleyeceðiz. Þimdilik herhangi bir þahýstan istemediðiniz özel mesajlar alýyorsanýz, pano yöneticisine baþvurun. O herhangi bir kullanýcýyý özel mesaj göndermekten men edebilir.");
$faq[] = array("Bu mesaj panosunda hesabý olan birinden spam e-posta aldým!", "Üzgünüz, aslýnda bu panonun sunduðu e-posta gönderme iþlevi bundan korunmak için birçok önlemi almýþ bulunuyor. Aldýðýnýz spam e-posta'nýn bir kopyasýný pano yöneticisine gönderin. Özellikle aldýðýnýz e-posta'nýn baþlýk kýsmýný (to (kime), subject (konu) vs.) iletmeyi unutmayýn, bu kýsýmda e-posta'yý gönderen kullanýcý hakkýnda bilgiler bulunur. Pano yöneticisi bu bilgilerle meseleyi takip edebilir.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","phpBB2 ile ilgili Konular");
$faq[] = array("Bu mesaj panosunu kim yazdý?", "Bu yazýlým (deðiþtirilmemiþ haliyle) <a href='http://www.phpbb.com/' target=\"_blank\">phpBB Group</a> tarafýndan üretilmiþ ve genel daðýtýma çýkarýlmýþtýr. Tüm eser haklarý phpBB Group'a aittir. Bu eser, '<a href='http://www.gnu.org/copyleft/gpl.html/' target='_blank'>GNU General Public Licence</a>' lisansýna uygun olarak eriþime açýlmýþtýr. Bu lisansa uyma þartýyla ücretsiz daðýtýlabilir.");

$faq[] = array("Bu mesaj panosunu kim Türkçeleþtirdi?", "Kullandýðýnýz Türkçe dil dosyalarý (deðiþtirilmemiþ haliyle) '<a href='http://www.canver.net/' title='Türkçe phpBB Topluluðu' target='_blank'>phpBB Türkiye</a>' tarafýndan çevrilmiþ ve genel daðýtýma sunulmuþtur. Tüm eser ve telif haklarý '<a href='http://www.canversoft.net/' title='Canver Biliþim ve Ýnternet Hizmetleri' target='_blank'>Canver Software</a>'a aittir. Bu dosyalar, '<a href='http://www.gnu.org/copyleft/gpl.html/' target='_blank'>GNU General Public Licence</a>' lisansýna uygun olarak eriþime açýlmýþtýr. Bu lisansa uyma þartýyla ücretsiz daðýtýlabilir, ancak dosyalardaki imza ve copyright gibi bilgiler deðiþtirilemez.");

$faq[] = array("Aradýðým ... özellik neden yok?", "Eðer herhangi bir özelliðin eksik olduðunu düþünüyorsanýz, lütfen phpbb.com sitesini ziyaret edip phpBB Group'un ilgili düþüncelerini öðrenin. Lütfen phpbb.com sitesindeki panoya yazýp yeni bir özellik isteðinde bulunmayýn. Yeni özellik taleplerinizi sourceforge aracýlýðýyla phpBB Group'a iletebilirsiniz. Lütfen ilgili forumlarý gezip ilk önce phpBB Group'un herhangi bir özellikle ilgili tutumunu öðrenin ve daha sonra burada tarif edilen yöntemle baþvuruda bulunun.");
$faq[] = array("Bu panoyla ilgili hukuki sorunlar için veya suistimal durumunda kime baþvurabilirim?", "Pano yöneticisine baþvurmanýz önerilir. Pano yöneticisinin kim olduðunu öðrenemezseniz, ilk önce bölüm yetkililerinden biriyle irtibata geçip, kime yazmanýz gerektiðini öðrenin. Herhangi bir yanýt alamadýðýnýz takdirde, site sahibine baþvurun (whois aramasýyla sitenin sahibini öðrenebilirsiniz) veya (eðer pano ücretsiz hizmet veren sitelerde çalýþtýrýlýyorsa, örn. Lycos, free.fr, f2s.com vs.) sitenin yönetimine veya suistimal konularýyla ilgilenen þubesine baþvurun. phpBB Group'un bu panonun nasýl, nerede ve kimler tarafýndan çalýþtýrýldýðýný kontrol etmediðini ve herhangi bir þekilde bundan sorumlu olmadýðýný lütfen dikkate alýn. phpbb.com sitesiyle veya phpBB yazýlýmýyla doðrudan ilgisi olmayan herhangi bir hukuki konuda (ihtiyati tedbir, mali sorumluluk, iftira vs.) phpBB Group'la irtibata geçmek tamamen anlamsýzdýr. Bu yazýlýmýn herhangi üçüncü þahýslar tarafýndan kullanýmýyla ilgili phpBB Group'a e-posta yazarsanýz, çok kýsa yada hiç cevap almamayý beklemeniz gerek.");
$faq[] = array("Bu yardýmcý bilgiler için kimlere teþekkür edebilirim?", "&#9642; <a href='http://www.phpbb.com/' target='_blank'>phpBB Group</a> - phpBB Resmi Sitesi<br /> &#9642; <a href='http://www.canver.net' title='Türkçe phpBB Topluluðu' target='_blank'>phpBB Türkiye</a> - phpBB yazýlýmýnýn Türkçe Desteðini saðlar<br />");



//
// This ends the FAQ entries
//-----------------------------

?>